/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}', './index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-tint": "#00e290",
        "on-background": "#e0e2ea",
        "secondary": "#bcc7de",
        "error": "#ffb4ab",
        "on-primary-container": "#007146",
        "tertiary-fixed-dim": "#d2bbff",
        "surface-dim": "#101419",
        "surface-container-lowest": "#0a0e13",
        "on-secondary": "#263143",
        "primary-fixed-dim": "#00e290",
        "on-tertiary-container": "#7834e9",
        "inverse-surface": "#e0e2ea",
        "on-primary-fixed-variant": "#005231",
        "secondary-fixed-dim": "#bcc7de",
        "surface-container-low": "#181c21",
        "error-container": "#93000a",
        "primary-container": "#00ffa3",
        "outline-variant": "#3a4a3f",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container-highest": "#31353b",
        "on-surface-variant": "#b9cbbd",
        "surface-container": "#1c2025",
        "background": "#101419",
        "primary-fixed": "#52ffac",
        "on-surface": "#e0e2ea",
        "on-tertiary-fixed": "#25005a",
        "surface-container-high": "#262a30",
        "inverse-primary": "#006d43",
        "primary": "#f5fff5",
        "tertiary": "#fffbff",
        "on-secondary-fixed": "#111c2d",
        "secondary-container": "#3e495d",
        "tertiary-container": "#e8d9ff",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#002111",
        "surface": "#101419",
        "on-tertiary": "#3f008e",
        "on-error": "#690005",
        "surface-variant": "#31353b",
        "secondary-fixed": "#d8e3fb",
        "outline": "#849588",
        "on-primary": "#003920",
        "on-tertiary-fixed-variant": "#5a00c6",
        "tertiary-fixed": "#eaddff",
        "on-secondary-container": "#aeb9d0",
        "surface-bright": "#36393f",
        "inverse-on-surface": "#2d3136",
      },
      fontFamily: {
        headline: ['Space Grotesk'],
        body: ['Manrope'],
        label: ['Inter'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  daisyui: {
    themes: [
      {
        algodark: {
          primary: '#00FFA3',
          'primary-content': '#003920',
          secondary: '#bcc7de',
          'secondary-content': '#e0e2ea',
          accent: '#00e290',
          'accent-content': '#003920',
          neutral: '#1c2025',
          'neutral-content': '#e0e2ea',
          'base-100': '#101419',
          'base-200': '#181c21',
          'base-300': '#262a30',
          'base-content': '#e0e2ea',
          info: '#00FFA3',
          success: '#00FFA3',
          warning: '#fbbf24',
          error: '#ffb4ab',
        },
      },
    ],
    logs: false,
  },
  plugins: [require('daisyui')],
}
